# CMake generated Testfile for 
# Source directory: /content/CMake/Tests/CMakeTests
# Build directory: /content/CMake/Tests/CMakeTests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[CMake.List]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/ListTest.cmake")
set_tests_properties([=[CMake.List]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;14;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.VariableWatch]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/VariableWatchTest.cmake")
set_tests_properties([=[CMake.VariableWatch]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;15;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Include]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/IncludeTest.cmake")
set_tests_properties([=[CMake.Include]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;16;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FindBase]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/FindBaseTest.cmake")
set_tests_properties([=[CMake.FindBase]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;17;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Toolchain]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/ToolchainTest.cmake")
set_tests_properties([=[CMake.Toolchain]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;18;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetFilenameComponentRealpath]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/GetFilenameComponentRealpathTest.cmake")
set_tests_properties([=[CMake.GetFilenameComponentRealpath]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;19;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Version]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/VersionTest.cmake")
set_tests_properties([=[CMake.Version]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;20;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Message]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/MessageTest.cmake")
set_tests_properties([=[CMake.Message]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;21;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.File]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/FileTest.cmake")
set_tests_properties([=[CMake.File]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;22;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ImplicitLinkInfo]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/ImplicitLinkInfoTest.cmake")
set_tests_properties([=[CMake.ImplicitLinkInfo]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;23;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ModuleNotices]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/ModuleNoticesTest.cmake")
set_tests_properties([=[CMake.ModuleNotices]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;24;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetProperty]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/GetPropertyTest.cmake")
set_tests_properties([=[CMake.GetProperty]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;25;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.If]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/IfTest.cmake")
set_tests_properties([=[CMake.If]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;26;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.String]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/StringTest.cmake")
set_tests_properties([=[CMake.String]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;27;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.Math]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/MathTest.cmake")
set_tests_properties([=[CMake.Math]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;28;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CMakeMinimumRequired]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/CMakeMinimumRequiredTest.cmake")
set_tests_properties([=[CMake.CMakeMinimumRequired]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;29;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CompilerIdVendor]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/CompilerIdVendorTest.cmake")
set_tests_properties([=[CMake.CompilerIdVendor]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;30;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.ProcessorCount]=] "/content/CMake/bin/cmake" "-DKWSYS_TEST_EXE=/content/CMake/Source/kwsys/cmsysTestsCxx" "-P" "/content/CMake/Tests/CMakeTests/ProcessorCountTest.cmake")
set_tests_properties([=[CMake.ProcessorCount]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;31;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PushCheckState]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/PushCheckStateTest.cmake")
set_tests_properties([=[CMake.PushCheckState]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;32;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.While]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/WhileTest.cmake")
set_tests_properties([=[CMake.While]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;33;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CMakeHostSystemInformation]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/CMakeHostSystemInformationTest.cmake")
set_tests_properties([=[CMake.CMakeHostSystemInformation]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;34;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FileDownload]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/FileDownloadTest.cmake")
set_tests_properties([=[CMake.FileDownload]=] PROPERTIES  FAIL_REGULAR_EXPRESSION "Unexpected status|incorrectly interpreted" LABELS "CMake;command" PASS_REGULAR_EXPRESSION "file already exists with expected MD5 sum" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;36;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FileDownloadBadHash]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/FileDownloadBadHashTest.cmake")
set_tests_properties([=[CMake.FileDownloadBadHash]=] PROPERTIES  LABELS "CMake;command" WILL_FAIL "TRUE" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;41;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.FileUpload]=] "/content/CMake/bin/cmake" "-P" "/content/CMake/Tests/CMakeTests/FileUploadTest.cmake")
set_tests_properties([=[CMake.FileUpload]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;46;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.EndStuff]=] "/content/CMake/bin/cmake" "-Ddir:STRING=/content/CMake/Tests/CMakeTests/EndStuffTest" "-P" "/content/CMake/Tests/CMakeTests/EndStuffTest.cmake")
set_tests_properties([=[CMake.EndStuff]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;51;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.GetPrerequisites]=] "/content/CMake/bin/cmake" "-DConfiguration:STRING=Release" "-P" "/content/CMake/Tests/CMakeTests/GetPrerequisitesTest.cmake")
set_tests_properties([=[CMake.GetPrerequisites]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;53;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.PolicyCheck]=] "/content/CMake/bin/cmake" "-DCMake_BINARY_DIR:PATH=/content/CMake" "-DCMake_SOURCE_DIR:PATH=/content/CMake" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-P" "/content/CMake/Tests/CMakeTests/PolicyCheckTest.cmake")
set_tests_properties([=[CMake.PolicyCheck]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;61;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
add_test([=[CMake.CheckSourceTree]=] "/content/CMake/bin/cmake" "-DCMake_BINARY_DIR:PATH=/content/CMake" "-DCMake_SOURCE_DIR:PATH=/content/CMake" "-DGIT_EXECUTABLE:STRING=/usr/bin/git" "-DHOME:STRING=/root" "-P" "/content/CMake/Tests/CMakeTests/CheckSourceTreeTest.cmake")
set_tests_properties([=[CMake.CheckSourceTree]=] PROPERTIES  LABELS "CMake;command" _BACKTRACE_TRIPLES "/content/CMake/Tests/CMakeTests/CMakeLists.txt;7;add_test;/content/CMake/Tests/CMakeTests/CMakeLists.txt;76;AddCMakeTest;/content/CMake/Tests/CMakeTests/CMakeLists.txt;0;")
